# Generated by Django 3.1.5 on 2021-01-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'Kgs'), ('gm', 'Grams'), ('l', 'Litres'), ('ml', 'Mililitres'), ('m', 'Metres'), ('cm', 'Centimetres')], default='kg', max_length=50)),
                ('status', models.CharField(choices=[('Bought', 'Bought'), ('Left', 'Left'), ('Not-Available', 'Not-Available')], default='L', max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
